[package]
name = "ticking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raft = "0.6"
slog = "2.7"
slog-stdlog = "4.1"
